title: faith
subtitle: leetcode学习
description: 技术笔记，leetcode学习
author: faith
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.nofile.cc
root: ''
permalink: posts/:category/:year/:month/:day/:title.html
permalink_defaults:

# custom Site settings
# more detail check out docs
SEOTitle: faith's blog
#cdn: 'header-off'
header-img: https://img.nofile.cc/banner.jpg
email: xiaolongnk@126.com
keyword: mysql , leetcode , php , nginx , linux ,shell , python , mac , mysql索引,https,programming, awk,sed,vim,阅读,kindle,dfs,算法

# custom end


# SNS settings
# RSS:
weibo_username: 5369993110
zhihu_username: ou-xiao-long-89
github_username: xiaolongnk
facebook_username:
linkedin_username:

# Build settings
anchorjs: false                        # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
disqus_username:

# Duoshuo settings
duoshuo_username:  nofile
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
ba_track_id: b98900c3864b32c37d696546d1911856
# Google Analytics
#ga_track_id:       # Format: UA-xxxxxx-xx
#ga_domain:

# Sidebar settings
sidebar: true
sidebar-about-description: 不忘初心,方能始终
sidebar-avatar: https://img.nofile.cc/icon.jpg


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0           # A tag will be featured if the size of it is more than this condition value

# friends
friends:  # 友链

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: Anisina

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
  repo:
  branch:


# img CDN path
#cdn-url:  # 你的CDN地址
# Qiniu imageView2 API
# More info http://developer.qiniu.com/code/v6/api/kodo-api/image/imageview2.html
#clip-content: http://blog.nofile.cc/css/images/banner.jpg
#"?imageView2/1/w/1400/h/400/interlace/1/q/90"
#clip-avatar: http://blog.nofile.cc/css/images/banner.jpg
#"?imageView2/2/w/300/h/300/interlace/1/q/90"
#clip-home-post-bg: http://blog.nofile.cc/css/images/banner.jpg
#"?imageView2/1/w/800/h/300/interlace/1/q/70"

# post default images
post-default-img: https://img.nofile.cc/banner.jpg
post-default-img-mobile: https://img.nofile.cc/banner.jpg
#移动端显示的图片

# search api , set your custom key
#swiftype_key:

